### ISSUE TITLE
Feature Request. Ability to add multiple printers/moonraker instances

### ISSUE THREAD

**Issue by screech24** [Kragrathea/pgcode#19]
Would be cool if there was a way to connect more than one printer/ Moonraker instance. I have 2 different printers on 1 pi and it would be amazing if you could switch between them.

**Comment by Kragrathea** [comment]
I don't know exactly how multiple printers work with Moonraker. But there would almost have to be one instance of Moonraker per printer, right? If so you should just be able to connect to the second instance with its port number. The fastest way to switch back and forth would be with two browser bookmarks.

**Comment by screech24** [comment]
I didn't even think of that lol. I Should have known that would work when I
saw the port #
You are right about there being 2 moonraker instances 1 port # for each
printer. I will use separate tabs that works perfect!

Appreciate the response.
