### ISSUE TITLE
moonraker update manager incompatible?

### ISSUE THREAD

**Issue by docgalaxyblock** [Kragrathea/pgcode#21]
Hi, I tried to setup the moonraker update manager to support pgcode.
I had no sucess...
so asked around some discords and someone told me that moonraker wants a version scheme like `v0.0.0`

Did you tried it yourself?

Greetings

**Comment by Kragrathea** [comment]
@docgalaxyblock I did a new release with a v1.12.0 version number. Let me know if that fixes this issue or not.

**Comment by docgalaxyblock** [comment]
Got it working now, thx.
I got this error now: `Repo not on valid remote branch, expected: origin/master, detected: origin/main`
But that is githubs change to the default branch ...
```
[update_manager pgcode]
type: git_repo
primary_branch: main
origin: https://github.com/Kragrathea/pgcode.git
path: ~/pgcode
is_system_service: False
```
Here is my current working update_manager pgcode config, feel free to add it to your repo doc

**Comment by Kragrathea** [comment]
@docgalaxyblock Thanks! Seems to work great. I updated the README.
