### ISSUE TITLE
Integrate Into fluidd web-ui

### ISSUE THREAD

**Issue by wieluk** [Kragrathea/pgcode#24]
Hey, is it possible to integrate this into the fluidd Web-ui like it was for octoprint?

**Comment by matmen** [comment]
You can embed it in Fluidd as a camera via an iframe:
![image](https://user-images.githubusercontent.com/25269274/192154969-0253d907-4cca-4a9a-8223-af325251ce1f.png)
![image](https://user-images.githubusercontent.com/25269274/192154982-1da5fff7-b16f-4931-b8b1-e912348f7a09.png)

**Comment by wieluk** [comment]
Thanks

**Comment by doublep21** [comment]
how to remove the blue statistics stuff?

**Comment by MarSoft** [comment]
@doublep21, I had to add custom adblock filter in my browser to remove this statistics stuff, as I could not find any "good" way to do that.
Also I'd like to change the default viewing angle, but could not do that either.

**Comment by matte-oss** [comment]
> You can embed it in Fluidd as a camera via an iframe:
> ![image](https://user-images.githubusercontent.com/25269274/192154969-0253d907-4cca-4a9a-8223-af325251ce1f.png)
> ![image](https://user-images.githubusercontent.com/25269274/192154982-1da5fff7-b16f-4931-b8b1-e912348f7a09.png)
> 

I know i'm late but can you please share the full link you used there?

**Comment by MarSoft** [comment]
The full link just includes pgcode settings like bed size.

сб, 28 сент. 2024 г., 19:39 masseo ***@***.***>:

**Comment by matte-oss** [comment]
Sorry, but what are those settings?

**Comment by matte-oss** [comment]
Oh nvm i forgot to set it to http page
