### ISSUE TITLE
Wrong display with Delta printers

### ISSUE THREAD

**Issue by susisstrolch** [Kragrathea/pgcode#3]
For printer with round printbed the display is wrong.
Object center is in lower left corner instead of bed center.

![grafik](https://user-images.githubusercontent.com/1432955/129320886-b646834b-7f37-4aa8-8f30-ff611f2a01c2.png)

**Comment by Kragrathea** [comment]
Thanks. I'll fix.

**Comment by Kragrathea** [comment]
I added a URL parameter to let you set the bed origin and volume in the latest version.  
Something like should work:
http://fluidpi.local:7136?bed.origin=center
@susisstrolch could you verify that fixes your issue?

**Comment by susisstrolch** [comment]
WIth bed.origin=center the 2D preview is wrong...
![grafik](https://user-images.githubusercontent.com/1432955/129477245-1fecf081-524b-4a22-8af2-eaeeab286968.png)

**Comment by susisstrolch** [comment]
> I added a URL parameter to let you set the bed origin and volume in the latest version.
Wouldn't a config parameter make more sense?

**Comment by Kragrathea** [comment]
Oops. I'll fix the 2d window. Yes, defaults will be a config eventually, but I don't have the code in place yet.

**Comment by Kragrathea** [comment]
Future version will detect bed size and origin automatically. I will leave this switch in until that version is released.
